name: conditional exp
on:
  workflow_dispatch
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: doing cron job
        run: echo haaktin pradeepa

  
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: working on concurrency
        run: echo concurrrr
          
  
  