name: my-sec-wf
on: push

jobs:
  my-sec-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: list and read files
        run: |
           echo " my sec job"
           ls - lrta
           cat README.md
      - name: install cowsay program
        run: sudo apt-get install cowsay -y
      - name: Generate ascii artwork
        run: cowsay -f dragon "RUN for cover, I am a DRAGON " >> dragon.txt
      - name: read the file
        run: cat dragon.txt
