name: matrix-stratergy
on:
  push

jobs:
  docker:
    strategy: 
      matrix: 
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude: 
          - images: alpine
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: docker login
        run: docker info
      - name: run the docker images
        run: docker run ${{ matrix.images }}

  