name: filter and activities
on:
  #workflow_dispatch:
  push:
    branches:
    - 'main' 
    - '!feature/*'
    # branches-ignore:
    #   - 'main'
    #   - 'main/*'
  pull_request:
    types:
      - opened
      - closed
    path-ignore:
      - README.md
    branches:
      - main
    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: docker info
        run: echo docker info